fix: converted UTC time to local time in all the bulk email history tables
openedx/frontend-app-communications pull request #195
Opened 2024-02-26 11:59 UTC by eemaanamir

The value of `created` of each email item in the table data is updated from UTC to the user's local time. The tables updated are BulkEmailTaskHistory and BulkEmailContentHistory.

### Before Change:
<img width="760" alt="Screenshot 2024-02-26 at 4 51 50 PM" src="https://github.com/openedx/frontend-app-communications/assets/57627710/49975240-b672-4beb-a380-a6602e045b56">

### After Change:
<img width="760" alt="Screenshot 2024-02-26 at 4 50 35 PM" src="https://github.com/openedx/frontend-app-communications/assets/57627710/b3d032f9-9c9c-4ea9-a228-a4a57c7e9629">

2024-02-26 11:59 UTC, openedx-webhooks commented
Thanks for the pull request, @eemaanamir! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by adding a comment here that you have signed it.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-02-26 17:43 UTC, mphilbrick211 commented
Hi @eemaanamir! Thank you for this contribution! Please let me know if you have any questions regarding submitting a CLA form.

If you are contributing on behalf of an organization (and not as an individual), please have your manager reach out to oscm@axim.org to have you added to your entity's agreement with us. Thank you!

2024-02-27 13:42 UTC, awais-ansari requested changes

2024-02-27 20:49 UTC, awais-ansari requested changes

2024-02-27 20:49 UTC, awais-ansari commented on src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailTaskHistory.jsx
> +
please memorize the function.

2024-02-27 20:49 UTC, awais-ansari commented on src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailContentHistory.jsx
>    }
please memorize the function.

2024-02-29 15:00 UTC, awais-ansari approved these changes

2024-02-29 18:18 UTC, arbrandes commented
Congrats @eemaanamir!  All that's missing for this to get merged is a signed CLA.

2024-03-06 08:57 UTC, ayesha-waris commented
Fix resolved in [PR](https://github.com/openedx/frontend-app-communications/pull/198) due to delay in CLA

2024-03-06 08:57 UTC, closed without merging

2024-03-06 08:57 UTC, openedx-webhooks commented
@eemaanamir Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-communications&entry.867055334=https://github.com/openedx/frontend-app-communications/pull/195&entry.1484655318=https://github.com/eemaanamir&entry.752974735=2024-02-26+11:59&entry.1917517419=2024-03-06+08:57&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->